import React, { useState, useEffect } from 'react';
import {
    Box, Card, Grid, Typography, Tabs, Tab, CircularProgress, Stack, Button, IconButton,
    Table, TableBody, TableCell, TableContainer, TableHead, TableRow, Dialog, DialogTitle,
    DialogContent, DialogActions, TextField, MenuItem, Chip, InputAdornment, Paper,
    TablePagination, alpha, useMediaQuery, useTheme, Tooltip
} from '@mui/material';
import { Store, Inventory2, ShoppingCart, Assessment, Add, Refresh, Edit, Delete, Search } from '@mui/icons-material';
import { useSnackbar } from 'notistack';
import { useForm, Controller } from 'react-hook-form';
import axios from 'axios';

const API_URL = `${process.env.REACT_APP_API_URL || 'http://localhost:8000'}/api/v1/inventory`;
const api = axios.create({ baseURL: API_URL, headers: { 'Content-Type': 'application/json' } });
api.interceptors.request.use(c => { const t = localStorage.getItem('token'); if (t) c.headers.Authorization = `Bearer ${t}`; return c; });

const EC = { activo: '#10b981', inactivo: '#ef4444' };
const SC = ({ title, value, icon, color, subtitle }) => (
    <Card sx={{ p: 3, borderRadius: 4, background: `linear-gradient(135deg, ${color}20, ${color}05)`, border: `1px solid ${alpha(color, 0.2)}`, transition: '0.3s', '&:hover': { transform: 'translateY(-4px)', boxShadow: `0 12px 24px ${alpha(color, 0.2)}` } }}>
        <Stack spacing={2}><Stack direction="row" justifyContent="space-between"><Box><Typography variant="body2" sx={{ color: '#6c757d', fontWeight: 500 }}>{title}</Typography><Typography variant="h3" sx={{ fontWeight: 700 }}>{value}</Typography>{subtitle && <Typography variant="caption" color="text.secondary">{subtitle}</Typography>}</Box><Box sx={{ width: 56, height: 56, borderRadius: 3, background: `linear-gradient(135deg, ${color}, ${alpha(color, 0.8)})`, display: 'flex', alignItems: 'center', justifyContent: 'center', boxShadow: `0 8px 16px ${alpha(color, 0.3)}` }}>{icon}</Box></Stack></Stack>
    </Card>
);

export default function Inventory() {
    const t = useTheme(), m = useMediaQuery(t.breakpoints.down('md')), { enqueueSnackbar: sn } = useSnackbar();
    const [tab, setTab] = useState(0), [load, setLoad] = useState(false), [stats, setStats] = useState({}), [q, setQ] = useState(''), [p, setP] = useState(0), [rp, setRp] = useState(10);
    const [vnd, setVnd] = useState([]), [prd, setPrd] = useState([]), [stk, setStk] = useState([]), [vnt, setVnt] = useState([]);
    const [open, setOpen] = useState(false), [type, setType] = useState(''), [edit, setEdit] = useState(null);
    const { control, handleSubmit, reset, formState: { errors } } = useForm();

    useEffect(() => { ls(); ld(); }, [tab, q]);

    const ls = async () => { try { setStats((await api.get('/estadisticas/general')).data); } catch (e) { console.error(e); } };
    const ld = async () => {
        setLoad(true);
        try {
            const params = { search: q, limit: 100 };
            if (tab === 0) setVnd((await api.get('/vendedores', { params })).data);
            else if (tab === 1) setPrd((await api.get('/productos', { params })).data);
            else if (tab === 2) setStk((await api.get('/stock', { params })).data);
            else if (tab === 3) setVnt((await api.get('/ventas', { params })).data);
        } catch (e) { sn('Error: ' + (e.response?.data?.detail || e.message), { variant: 'error' }); }
        finally { setLoad(false); }
    };
    const fc = v => new Intl.NumberFormat('es-CO', { style: 'currency', currency: 'COP', minimumFractionDigits: 0 }).format(v || 0);
    const od = (tp, it = null) => { setType(tp); setEdit(it); reset(it || {}); setOpen(true); };
    const cd = () => { setOpen(false); setEdit(null); reset({}); };
    const os = async fd => {
        try {
            if (type === 'vendedor') edit ? await api.put(`/vendedores/${edit.id}`, fd) : await api.post('/vendedores', fd);
            else if (type === 'producto') edit ? await api.put(`/productos/${edit.id}`, fd) : await api.post('/productos', fd);
            else if (type === 'stock') await api.post('/stock/asignar', fd);
            else if (type === 'venta') edit ? await api.put(`/ventas/${edit.id}`, fd) : await api.post('/ventas', fd);
            sn(`${edit ? 'Actualizado' : 'Creado'}`, { variant: 'success' }); cd(); ld(); ls();
        } catch (e) { sn(e.response?.data?.detail || 'Error', { variant: 'error' }); }
    };
    const del = async (tp, id) => {
        if (!window.confirm('¿Eliminar?')) return;
        try { await api.delete(`/${tp === 'vendedor' ? 'vendedores' : tp === 'producto' ? 'productos' : 'ventas'}/${id}`); sn('Eliminado', { variant: 'success' }); ld(); ls(); }
        catch (e) { sn('Error', { variant: 'error' }); }
    };
    const Act = ({ tp, it }) => (<Box sx={{ display: 'flex', gap: 0.5 }}><Tooltip title="Editar"><IconButton size="small" onClick={() => od(tp, it)} sx={{ color: '#3b82f6' }}><Edit fontSize="small" /></IconButton></Tooltip>{tp !== 'stock' && <Tooltip title="Eliminar"><IconButton size="small" onClick={() => del(tp, it.id)} sx={{ color: '#ef4444' }}><Delete fontSize="small" /></IconButton></Tooltip>}</Box>);
    const rt = (d, cols, tp) => (<TableContainer component={Paper} sx={{ boxShadow: 'none', border: '1px solid #e5e7eb', borderRadius: 2 }}><Table><TableHead sx={{ bgcolor: '#f9fafb' }}><TableRow>{cols.map(c => <TableCell key={c.label} align={c.align || 'left'} sx={{ fontWeight: 600 }}>{c.label}</TableCell>)}<TableCell align="right" sx={{ fontWeight: 600 }}>Acciones</TableCell></TableRow></TableHead><TableBody>{d.slice(p * rp, p * rp + rp).map(r => <TableRow key={r.id} hover sx={{ '&:hover': { backgroundColor: alpha('#34d399', 0.04) } }}>{cols.map(c => <TableCell key={c.label} align={c.align || 'left'}>{c.render ? c.render(r) : r[c.key] || '-'}</TableCell>)}<TableCell align="right"><Act tp={tp} it={r} /></TableCell></TableRow>)}</TableBody></Table><TablePagination component="div" count={d.length} page={p} onPageChange={(e, n) => setP(n)} rowsPerPage={rp} onRowsPerPageChange={e => { setRp(parseInt(e.target.value, 10)); setP(0); }} labelRowsPerPage="Filas:" /></TableContainer>);
    const rdc = () => {
        const gs = { mt: 0.5 }, sz = m ? 'small' : 'medium';
        if (type === 'vendedor') return (<Grid container spacing={2} sx={gs}><Grid item xs={12} sm={6}><Controller name="nombre" control={control} rules={{ required: 'Requerido' }} render={({ field }) => <TextField {...field} fullWidth label="Nombre *" error={!!errors.nombre} helperText={errors.nombre?.message} size={sz} />} /></Grid><Grid item xs={12} sm={6}><Controller name="telefono" control={control} rules={{ required: 'Requerido' }} render={({ field }) => <TextField {...field} fullWidth label="Teléfono *" error={!!errors.telefono} helperText={errors.telefono?.message} size={sz} />} /></Grid><Grid item xs={12} sm={6}><Controller name="ciudad" control={control} render={({ field }) => <TextField {...field} fullWidth label="Ciudad" size={sz} />} /></Grid><Grid item xs={12} sm={6}><Controller name="estado" control={control} defaultValue="activo" render={({ field }) => <TextField {...field} select fullWidth label="Estado *" size={sz}><MenuItem value="activo">Activo</MenuItem><MenuItem value="inactivo">Inactivo</MenuItem></TextField>} /></Grid><Grid item xs={12}><Controller name="direccion" control={control} render={({ field }) => <TextField {...field} fullWidth label="Dirección" multiline rows={2} size={sz} />} /></Grid></Grid>);
        if (type === 'producto') return (<Grid container spacing={2} sx={gs}><Grid item xs={12} sm={6}><Controller name="nombre" control={control} rules={{ required: 'Requerido' }} render={({ field }) => <TextField {...field} fullWidth label="Nombre *" error={!!errors.nombre} helperText={errors.nombre?.message} size={sz} />} /></Grid><Grid item xs={12} sm={6}><Controller name="codigo" control={control} render={({ field }) => <TextField {...field} fullWidth label="Código" size={sz} />} /></Grid><Grid item xs={12} sm={6}><Controller name="categoria" control={control} render={({ field }) => <TextField {...field} fullWidth label="Categoría" size={sz} />} /></Grid><Grid item xs={12} sm={6}><Controller name="precio_unitario" control={control} rules={{ required: 'Requerido', min: { value: 0, message: 'Mayor a 0' } }} render={({ field }) => <TextField {...field} fullWidth label="Precio *" type="number" error={!!errors.precio_unitario} helperText={errors.precio_unitario?.message} size={sz} InputProps={{ startAdornment: <InputAdornment position="start">$</InputAdornment> }} />} /></Grid><Grid item xs={12} sm={6}><Controller name="estado" control={control} defaultValue="activo" render={({ field }) => <TextField {...field} select fullWidth label="Estado *" size={sz}><MenuItem value="activo">Activo</MenuItem><MenuItem value="inactivo">Inactivo</MenuItem></TextField>} /></Grid><Grid item xs={12}><Controller name="descripcion" control={control} render={({ field }) => <TextField {...field} fullWidth label="Descripción" multiline rows={2} size={sz} />} /></Grid></Grid>);
        if (type === 'stock') return (<Grid container spacing={2} sx={gs}><Grid item xs={12} sm={6}><Controller name="vendedor_id" control={control} rules={{ required: 'Requerido' }} render={({ field }) => <TextField {...field} select fullWidth label="Vendedor *" error={!!errors.vendedor_id} helperText={errors.vendedor_id?.message} size={sz}>{vnd.filter(v => v.estado === 'activo').map(v => <MenuItem key={v.id} value={v.id}>{v.nombre}</MenuItem>)}</TextField>} /></Grid><Grid item xs={12} sm={6}><Controller name="producto_id" control={control} rules={{ required: 'Requerido' }} render={({ field }) => <TextField {...field} select fullWidth label="Producto *" error={!!errors.producto_id} helperText={errors.producto_id?.message} size={sz}>{prd.filter(p => p.estado === 'activo').map(p => <MenuItem key={p.id} value={p.id}>{p.nombre}</MenuItem>)}</TextField>} /></Grid><Grid item xs={12}><Controller name="cantidad" control={control} rules={{ required: 'Requerido', min: { value: 1, message: 'Mín 1' } }} render={({ field }) => <TextField {...field} fullWidth label="Cantidad *" type="number" error={!!errors.cantidad} helperText={errors.cantidad?.message} size={sz} />} /></Grid></Grid>);
        if (type === 'venta') return (<Grid container spacing={2} sx={gs}><Grid item xs={12} sm={6}><Controller name="vendedor_id" control={control} rules={{ required: 'Requerido' }} render={({ field }) => <TextField {...field} select fullWidth label="Vendedor *" error={!!errors.vendedor_id} helperText={errors.vendedor_id?.message} size={sz}>{vnd.filter(v => v.estado === 'activo').map(v => <MenuItem key={v.id} value={v.id}>{v.nombre}</MenuItem>)}</TextField>} /></Grid><Grid item xs={12} sm={6}><Controller name="producto_id" control={control} rules={{ required: 'Requerido' }} render={({ field }) => <TextField {...field} select fullWidth label="Producto *" error={!!errors.producto_id} helperText={errors.producto_id?.message} size={sz}>{prd.filter(p => p.estado === 'activo').map(p => <MenuItem key={p.id} value={p.id}>{p.nombre}</MenuItem>)}</TextField>} /></Grid><Grid item xs={12} sm={6}><Controller name="cantidad" control={control} rules={{ required: 'Requerido', min: { value: 1, message: 'Mín 1' } }} render={({ field }) => <TextField {...field} fullWidth label="Cantidad *" type="number" error={!!errors.cantidad} helperText={errors.cantidad?.message} size={sz} />} /></Grid><Grid item xs={12} sm={6}><Controller name="precio_venta" control={control} rules={{ required: 'Requerido', min: { value: 0, message: 'Mayor a 0' } }} render={({ field }) => <TextField {...field} fullWidth label="Precio *" type="number" error={!!errors.precio_venta} helperText={errors.precio_venta?.message} size={sz} InputProps={{ startAdornment: <InputAdornment position="start">$</InputAdornment> }} />} /></Grid><Grid item xs={12}><Controller name="notas" control={control} render={({ field }) => <TextField {...field} fullWidth label="Notas" multiline rows={2} size={sz} />} /></Grid></Grid>);
    };
    const sc = [
        { title: 'Vendedores Activos', value: stats.total_vendedores || 0, icon: <Store sx={{ fontSize: 28, color: '#fff' }} />, color: '#3b82f6' },
        { title: 'Productos', value: stats.total_productos || 0, icon: <Inventory2 sx={{ fontSize: 28, color: '#fff' }} />, color: '#34d399' },
        { title: 'Stock Total', value: stats.stock_total || 0, icon: <Assessment sx={{ fontSize: 28, color: '#fff' }} />, color: '#f59e0b', subtitle: fc(stats.valor_inventario) },
        { title: 'Ventas del Mes', value: stats.ventas_mes || 0, icon: <ShoppingCart sx={{ fontSize: 28, color: '#fff' }} />, color: '#8b5cf6', subtitle: fc(stats.valor_ventas_mes) }
    ];

    return (
        <Box sx={{ px: { xs: 1, sm: 2 }, py: 2 }}>
            <Stack direction="row" justifyContent="space-between" alignItems="center" mb={3}><Box><Typography variant="h4" sx={{ fontWeight: 700, fontSize: { xs: '1.5rem', sm: '2rem' } }}>Gestión de Inventario</Typography><Typography variant="body2" color="text.secondary">Control de centros de distribución</Typography></Box><IconButton onClick={() => { ld(); ls(); }} sx={{ bgcolor: alpha('#34d399', 0.15), '&:hover': { bgcolor: alpha('#34d399', 0.25) } }}><Refresh sx={{ color: '#34d399' }} /></IconButton></Stack>
            <Grid container spacing={3} mb={3}>{sc.map((c, i) => <Grid item xs={12} sm={6} lg={3} key={i}><SC {...c} /></Grid>)}</Grid>
            <Card sx={{ borderRadius: 3, border: '1px solid #e5e7eb' }}><Box sx={{ borderBottom: 1, borderColor: 'divider', px: 2 }}><Tabs value={tab} onChange={(e, v) => { setTab(v); setP(0); }} sx={{ '& .MuiTab-root': { textTransform: 'none', fontWeight: 600 }, '& .Mui-selected': { color: '#34d399' }, '& .MuiTabs-indicator': { bgcolor: '#34d399' } }}><Tab label="Vendedores" icon={<Store />} iconPosition="start" /><Tab label="Productos" icon={<Inventory2 />} iconPosition="start" /><Tab label="Stock" icon={<Assessment />} iconPosition="start" /><Tab label="Ventas" icon={<ShoppingCart />} iconPosition="start" /></Tabs></Box>
                <Box p={3}><Stack direction="row" spacing={2} mb={3}><TextField placeholder="Buscar..." size={m ? 'small' : 'medium'} value={q} onChange={e => setQ(e.target.value)} InputProps={{ startAdornment: <InputAdornment position="start"><Search /></InputAdornment> }} sx={{ flexGrow: 1 }} /><Button variant="contained" startIcon={<Add />} onClick={() => od(['vendedor', 'producto', 'stock', 'venta'][tab])} size={m ? 'medium' : 'large'} sx={{ background: 'linear-gradient(135deg, #34d399, #10b981)', color: '#fff', fontWeight: 600, '&:hover': { background: 'linear-gradient(135deg, #10b981, #059669)' } }}>Nuevo</Button></Stack>
                    {load ? <Box display="flex" justifyContent="center" py={4}><CircularProgress sx={{ color: '#34d399' }} /></Box> : <>{tab === 0 && rt(vnd, [{ label: 'Nombre', key: 'nombre' }, { label: 'Teléfono', key: 'telefono' }, { label: 'Ciudad', key: 'ciudad' }, { label: 'Estado', key: 'estado', render: r => <Chip label={r.estado} size="small" sx={{ bgcolor: alpha(EC[r.estado] || '#6c757d', 0.15), color: EC[r.estado] || '#6c757d', fontWeight: 600 }} /> }], 'vendedor')}{tab === 1 && rt(prd, [{ label: 'Nombre', key: 'nombre' }, { label: 'Código', key: 'codigo' }, { label: 'Categoría', key: 'categoria' }, { label: 'Precio', key: 'precio_unitario', align: 'right', render: r => fc(r.precio_unitario) }, { label: 'Estado', key: 'estado', render: r => <Chip label={r.estado} size="small" sx={{ bgcolor: alpha(EC[r.estado] || '#6c757d', 0.15), color: EC[r.estado] || '#6c757d', fontWeight: 600 }} /> }], 'producto')}{tab === 2 && rt(stk, [{ label: 'Vendedor', key: 'vendedor', render: r => r.vendedor?.nombre || '-' }, { label: 'Producto', key: 'producto', render: r => r.producto?.nombre || '-' }, { label: 'Stock Inicial', key: 'cantidad_inicial', align: 'right' }, { label: 'Stock Actual', key: 'cantidad_actual', align: 'right', render: r => <Chip label={r.cantidad_actual} sx={{ bgcolor: r.cantidad_actual > 0 ? alpha('#10b981', 0.15) : alpha('#ef4444', 0.15), color: r.cantidad_actual > 0 ? '#10b981' : '#ef4444', fontWeight: 600 }} size="small" /> }, { label: 'Última Act.', key: 'ultima_actualizacion', render: r => r.ultima_actualizacion ? new Date(r.ultima_actualizacion).toLocaleDateString() : '-' }], 'stock')}{tab === 3 && rt(vnt, [{ label: 'Fecha', key: 'fecha_venta', render: r => new Date(r.fecha_venta).toLocaleDateString() }, { label: 'Vendedor', key: 'vendedor', render: r => r.vendedor?.nombre || '-' }, { label: 'Producto', key: 'producto', render: r => r.producto?.nombre || '-' }, { label: 'Cantidad', key: 'cantidad', align: 'right' }, { label: 'Precio', key: 'precio_venta', align: 'right', render: r => fc(r.precio_venta) }, { label: 'Total', align: 'right', render: r => fc(r.cantidad * r.precio_venta) }], 'venta')}</>}</Box>
            </Card>
            <Dialog open={open} onClose={cd} maxWidth="md" fullWidth fullScreen={m}><form onSubmit={handleSubmit(os)}><DialogTitle sx={{ fontWeight: 600 }}>{edit ? 'Editar' : 'Crear'} {type === 'vendedor' ? 'Vendedor' : type === 'producto' ? 'Producto' : type === 'stock' ? 'Stock' : 'Venta'}</DialogTitle><DialogContent>{rdc()}</DialogContent><DialogActions sx={{ p: { xs: 1.5, sm: 2.5 } }}><Button onClick={cd} size={m ? 'medium' : 'large'}>Cancelar</Button><Button type="submit" variant="contained" size={m ? 'medium' : 'large'} sx={{ background: 'linear-gradient(135deg, #34d399, #10b981)', color: '#fff', fontWeight: 600, '&:hover': { background: 'linear-gradient(135deg, #10b981, #059669)' } }}>{edit ? 'Actualizar' : 'Crear'}</Button></DialogActions></form></Dialog>
        </Box>
    );
}